# 블로그 기본 설정
title: 내 블로그
description: GitHub Pages로 만든 나의 블로그
author: juyeo
email: your-email@example.com

# GitHub Pages 설정
baseurl: "/blog"
url: "https://juyeon0401.github.io"

# 테마 설정 - Cayman 테마 (깔끔하고 모던한 디자인)
remote_theme: pages-themes/cayman@v0.2.0

# 빌드 설정
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate

# 페이지네이션
paginate: 10
paginate_path: "/page:num/"

# 기타 설정
timezone: Asia/Seoul
lang: ko

# Permalink 설정 - 한글 카테고리 문제 해결
permalink: /:year/:month/:day/:title/

# SNS 링크 (선택사항)
github_username: juyeon0401
# twitter_username: your-twitter-username
